---
- name: CREATE ARM Deployment PLAYBOOK
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    templateLink: 'https://raw.githubusercontent.com/nitinpokharna/java/master/azuredeploywaf.json'
       
  tasks:
  - name: Deploy ARM template
    azure_rm_deployment:
        state: present
        resource_group_name: "ENYrg"
        # location seems to be not optional
        location: "West Europe"
        template_link: '{{ templateLink }}'
        parameters:
          capacity:
            value: 2
          virtualNetworkName: 
            value: "nitinnw"
          subnetName: 
            value: "nitinsub"
          applicationGatewayName: 
            value: "nitingateway"
          publicIPAddressName: 
            value: "nitinpubip"
          location: 
            value: "West Europe"
  - name: AZ Login to Azure
    shell: >
           az login --service-principal
           -u "{{ AZURE_RM_CLIENTID | mandatory }}"
           -p "{{ AZURE_RM_SECRET | mandatory }}"
           --tenant "{{ AZURE_RM_TENANTID | mandatory }}"
  - name: az commands on Gateway
    shell: |
           az network application-gateway address-pool create -g ENYrg --gateway-name nitingateway -n new --servers nitinwebapp12.azurewebsites.net
           az network application-gateway probe create -g ENYrg --gateway-name nitingateway --name  nitin --protocol http --host-name-from-http-settings true --path /
           az network application-gateway http-settings create -g ENYrg --gateway-name nitingateway -n MyHttpSettings --port 80 --protocol Http --cookie-based-affinity Disabled --enable-probe true --probe nitin --protocol http --timeout 30
           az network application-gateway http-listener create -g ENYrg --gateway-name nitingateway --frontend-port MyFrontendPort -n MyHttpListener
           az network application-gateway rule create -g ENYrg --gateway-name nitingateway -n MyRule --http-listener MyHttpListener --rule-type Basic --address-pool new --http-settings MyHttpSettings
