---
- name: CREATE ARM Deployment PLAYBOOK
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    templateLink: 'https://raw.githubusercontent.com/nitinpokharna/java/master/azuredeploywaf.json'
       
  tasks:
  - name: Deploy ARM template
    azure_rm_deployment:
        state: present
        resource_group_name: "eyrg"
        # location seems to be not optional
        location: "West Europe"
        template_link: '{{ templateLink }}'
        parameters:
          capacity:
            value: 2
          virtualNetworkName: 
            value: "nitinnwe"
          subnetName: 
            value: "nitinsube"
          applicationGatewayName: 
            value: "nitingateways"
          publicIPAddressName: 
            value: "nitinpubipp"
          location: 
            value: "West Europe"
  - name: AZ Login to Azure
    shell: >
           az login --service-principal
           -u "{{ AZURE_RM_CLIENTID | mandatory }}"
           -p "{{ AZURE_RM_SECRET | mandatory }}"
           --tenant "{{ AZURE_RM_TENANTID | mandatory }}"
  - name: az commands on Gateway
    shell: |
           az network application-gateway address-pool create -g eyrg --gateway-name nitingateways -n new --servers nitinwebapp12.azurewebsites.net --output json echo '----------------------------------'
           az network application-gateway probe create -g eyrg --gateway-name nitingateways --name  nitin --protocol http --host-name-from-http-settings true --path / --output json echo '----------------------------------'
           az network application-gateway frontend-port create -g eyrg --gateway-name nitingateways -n MyFrontendPort --port 8080 --output json echo '----------------------------------'
           az network application-gateway http-listener create -g eyrg --gateway-name nitingateways --frontend-port MyFrontendPort -n MyHttpListener --output json echo '----------------------------------'
           az network application-gateway rule create -g eyrg --gateway-name nitingateways -n MyRule --http-listener MyBackendListener --rule-type Basic --address-pool MyAddressPool --http-settings MyHttpSettings --output json echo '----------------------------------'
           az network application-gateway http-settings create -g eyrg --gateway-name nitingateways MyHttpSettings --port 80 --protocol Http --cookie-based-affinity Disabled --timeout 30 --output json echo '----------------------------------'
